[project]
name = "manim-projects"
version = "1.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "manim>=0.19.0",
    "matplotlib>=3.10.6",
    "pyqt6>=6.9.1",
    "tqdm>=4.67.1",
]
